base_path: "."
base_url: "https://api.crowdin.com"

preserve_hierarchy: true

languages_mapping:
  two_letters_code:
    ar: ar
    az: az
    bn: bn
    da: da
    de: de
    el: el
    es: es
    es-ES: es
    fi: fi
    fr: fr
    ga: ga
    ga-IE: ga
    hi: hi
    id: id
    it: it
    nl: nl
    no: no
    pl: pl
    pt: pt
    pt-PT: pt
    ro: ro
    ru: ru
    sq: sq
    sv: sv
    sv-SE: sv
    te: te
    tr: tr
    uk: uk
    vi: vi
    zh: zh
    zh-CN: zh

files:
  - source: /lib/l10n/app_en.arb
    translation: /lib/l10n/app_%two_letters_code%.arb
    update_option: update_as_unapproved
