import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:just_audio/just_audio.dart';
import 'package:uuid/uuid.dart';
import '../models/models.dart';
import 'library_database_service.dart';
import 'subsonic_service.dart';
import 'ytdlp_service.dart';

/// Proxies the YouTube audio stream via Dart's HttpClient to provide matching
/// headers (User-Agent, Range) and completely avoid HTTP 403 on ExoPlayer / Media3.
class _YoutubeStreamAudioSource extends StreamAudioSource {
  final String _videoId;
  final YtDlpService _ytdlp;

  _YoutubeStreamAudioSource(this._videoId, this._ytdlp) : super(tag: _videoId);

  @override
  Future<StreamAudioResponse> request([int? start, int? end]) async {
    final cleanId = _videoId.replaceFirst('ytmusic://', '');
    final streamInfo = await _ytdlp.resolveStreamInfo(cleanId);

    final s = start ?? 0;
    final client = HttpClient();

    try {
      final req = await client.getUrl(Uri.parse(streamInfo.url));

      // Apply exact HTTP headers generated by yt-dlp (User-Agent, Referer, Accept, etc.)
      streamInfo.headers.forEach((key, value) {
        final lower = key.toLowerCase();
        if (lower != 'host' && lower != 'content-length') {
          req.headers.set(key, value);
        }
      });

      if (end != null) {
        req.headers.set('Range', 'bytes=$s-$end');
      } else if (s > 0) {
        req.headers.set('Range', 'bytes=$s-');
      }

      final resp = await req.close();

      if (resp.statusCode == 403 || resp.statusCode == 429) {
        debugPrint('[YouTube] Stream rejected (${resp.statusCode}) for $cleanId, refreshing with forceRefresh...');
        _ytdlp.invalidateCache(cleanId);
        final freshInfo = await _ytdlp.resolveStreamInfo(cleanId, forceRefresh: true);
        final retryReq = await client.getUrl(Uri.parse(freshInfo.url));
        freshInfo.headers.forEach((key, value) {
          final lower = key.toLowerCase();
          if (lower != 'host' && lower != 'content-length') {
            retryReq.headers.set(key, value);
          }
        });
        if (end != null) {
          retryReq.headers.set('Range', 'bytes=$s-$end');
        } else if (s > 0) {
          retryReq.headers.set('Range', 'bytes=$s-');
        }
        final retryResp = await retryReq.close();
        if (retryResp.statusCode >= 400) {
          throw Exception('GoogleVideo stream rejected with HTTP ${retryResp.statusCode}');
        }
        return _buildResponse(retryResp, s, freshInfo.ext);
      }

      if (resp.statusCode >= 400) {
        throw Exception('GoogleVideo stream error: HTTP ${resp.statusCode}');
      }

      return _buildResponse(resp, s, streamInfo.ext);
    } catch (e) {
      debugPrint('[YouTube] StreamAudioSource request error for $cleanId: $e');
      rethrow;
    }
  }

  StreamAudioResponse _buildResponse(HttpClientResponse resp, int start, String ext) {
    final total = resp.contentLength >= 0 ? resp.contentLength + start : null;
    final isWebm = (ext == 'webm' || ext == 'opus');
    final type = isWebm ? 'audio/webm' : 'audio/mp4';

    return StreamAudioResponse(
      sourceLength: total,
      contentLength: resp.contentLength >= 0 ? resp.contentLength : null,
      offset: start,
      stream: resp,
      contentType: type,
    );
  }
}

class YoutubeService {
  final YtDlpService _ytdlp = YtDlpService();
  final LibraryDatabaseService _db = LibraryDatabaseService();

  void dispose() {
    _ytdlp.dispose();
  }

  // ── Connectivity ──────────────────────────────────────────────────────────

  Future<PingResult> pingWithError() async {
    try {
      final req = await HttpClient().getUrl(
        Uri.parse('https://music.youtube.com/'),
      );
      req.headers.set('User-Agent', 'Mozilla/5.0');
      final res = await req.close();
      await res.drain<void>();
      return PingResult(
        success: res.statusCode < 400,
        serverType: 'YT Stream (yt-dlp)',
        serverVersion: '1.0',
      );
    } catch (e) {
      return PingResult(success: false, error: 'Cannot reach YouTube: $e');
    }
  }

  // ── Cover art & stream ────────────────────────────────────────────────────

  String getCoverArtUrl(String? id, {int size = 300}) {
    if (id == null || id.isEmpty) return '';
    if (id.startsWith('http://') || id.startsWith('https://')) return id;
    if (RegExp(r'^[a-zA-Z0-9_-]{11}$').hasMatch(id)) {
      return 'https://img.youtube.com/vi/$id/mqdefault.jpg';
    }
    return '';
  }

  /// Returns a lightweight valid stream URL synchronously.
  String getStreamUrl(String videoId) =>
      'https://www.youtube.com/watch?v=${videoId.replaceFirst('ytmusic://', '')}';

  /// Resolves the actual direct audio stream URL via yt-dlp / Python process.
  Future<String> resolveStreamUrl(String videoId) async {
    final cleanId = videoId.replaceFirst('ytmusic://', '');
    return await _ytdlp.resolveStreamUrl(cleanId);
  }

  /// Builds a [StreamAudioSource] that proxies audio through Dart's HttpClient
  /// with standard browser headers to prevent HTTP 403 on ExoPlayer / Media3.
  Future<StreamAudioSource> buildAudioSource(String videoId) async {
    return _YoutubeStreamAudioSource(videoId, _ytdlp);
  }

  // ── Model mappers ─────────────────────────────────────────────────────────

  Song _mapDictToSong(Map<String, dynamic> d) {
    final id = d['id'] as String;
    final thumb = d['thumbnailUrl'] as String?;
    return Song(
      id: id,
      title: d['title'] as String? ?? 'Unknown Title',
      artist: d['artist'] as String? ?? 'Unknown Artist',
      album: d['album'] as String?,
      duration: d['duration'] as int?,
      coverArt: (thumb != null && thumb.isNotEmpty) ? thumb : (d['coverArt'] as String? ?? id),
    );
  }

  // ── Artists / Albums ──────────────────────────────────────────────────────

  Future<List<Artist>> getArtists() async {
    try {
      final songs = await _db.getAllSongs();
      final artistNames = <String>{};
      final artists = <Artist>[];

      for (final s in songs) {
        if (s.artist != null && s.artist!.isNotEmpty && !artistNames.contains(s.artist)) {
          artistNames.add(s.artist!);
          artists.add(Artist(
            id: s.artistId ?? s.artist!,
            name: s.artist!,
            coverArt: s.coverArt,
          ));
        }
      }
      return artists;
    } catch (e) {
      debugPrint('[YouTube] getArtists error: $e');
      return [];
    }
  }

  Future<List<Album>> getAlbumList({
    String type = 'recent',
    int size = 20,
    int offset = 0,
  }) async {
    try {
      final albums = await _db.getAllAlbums();
      if (albums.isNotEmpty) {
        return albums.skip(offset).take(size).toList();
      }

      // If local albums table is empty, generate album groupings from saved songs
      final songs = await _db.getAllSongs();
      final albumMap = <String, Album>{};
      for (final s in songs) {
        if (s.album != null && s.album!.isNotEmpty && !albumMap.containsKey(s.album)) {
          albumMap[s.album!] = Album(
            id: s.albumId ?? s.album!,
            name: s.album!,
            artist: s.artist,
            coverArt: s.coverArt,
          );
        }
      }
      return albumMap.values.skip(offset).take(size).toList();
    } catch (e) {
      debugPrint('[YouTube] getAlbumList error: $e');
      return [];
    }
  }

  Future<Album> getAlbum(String playlistOrAlbumId) async {
    try {
      final songs = await getAlbumSongs(playlistOrAlbumId);
      return Album(
        id: playlistOrAlbumId,
        name: songs.isNotEmpty ? (songs.first.album ?? 'Album') : 'Album',
        artist: songs.isNotEmpty ? songs.first.artist : 'Artist',
        coverArt: playlistOrAlbumId,
        songCount: songs.length,
      );
    } catch (e) {
      debugPrint('[YouTube] getAlbum error: $e');
      return Album(id: playlistOrAlbumId, name: 'Album');
    }
  }

  Future<List<Song>> getAlbumSongs(String albumId) async {
    try {
      // Check if it's a playlist or album in SQLite
      final songs = await _db.getAllSongs();
      final matching = songs.where((s) => s.albumId == albumId || s.album == albumId).toList();
      if (matching.isNotEmpty) return matching;

      // Otherwise fetch online via yt-dlp
      final videos = await _ytdlp.getPlaylistVideos(albumId);
      return videos.map(_mapDictToSong).toList();
    } catch (e) {
      debugPrint('[YouTube] getAlbumSongs error: $e');
      return [];
    }
  }

  Future<List<Album>> getArtistAlbums(String channelOrArtistId) async {
    try {
      final songs = await _db.getAllSongs();
      final artistSongs = songs.where((s) => s.artistId == channelOrArtistId || s.artist == channelOrArtistId).toList();
      final albumMap = <String, Album>{};
      for (final s in artistSongs) {
        if (s.album != null && s.album!.isNotEmpty && !albumMap.containsKey(s.album)) {
          albumMap[s.album!] = Album(
            id: s.albumId ?? s.album!,
            name: s.album!,
            artist: s.artist,
            coverArt: s.coverArt,
          );
        }
      }
      return albumMap.values.toList();
    } catch (e) {
      debugPrint('[YouTube] getArtistAlbums error: $e');
      return [];
    }
  }

  // ── Playlists (Locally Saved in SQLite) ───────────────────────────────────

  Future<List<Playlist>> getPlaylists() async {
    try {
      return await _db.getAllPlaylists();
    } catch (e) {
      debugPrint('[YouTube] getPlaylists error: $e');
      return [];
    }
  }

  Future<Playlist> getPlaylist(String id) async {
    try {
      final local = await _db.getPlaylist(id);
      if (local != null) return local;

      // Online YouTube playlist fallback
      final items = await _ytdlp.getPlaylistVideos(id);
      final songs = items.map(_mapDictToSong).toList();
      return Playlist(
        id: id,
        name: 'YouTube Playlist',
        songCount: songs.length,
        songs: songs,
      );
    } catch (e) {
      debugPrint('[YouTube] getPlaylist error: $e');
      return Playlist(id: id, name: 'Playlist');
    }
  }

  Future<void> createPlaylist({
    required String name,
    String? comment,
    List<String>? songIds,
  }) async {
    try {
      final newId = const Uuid().v4();
      List<Song>? songs;
      if (songIds != null && songIds.isNotEmpty) {
        songs = await _db.getSongs(songIds);
      }

      final playlist = Playlist(
        id: newId,
        name: name,
        comment: comment,
        owner: 'Local',
        songCount: songs?.length ?? songIds?.length ?? 0,
        created: DateTime.now(),
        changed: DateTime.now(),
        coverArt: songs?.isNotEmpty == true ? songs!.first.coverArt : null,
        songs: songs,
      );

      await _db.insertOrUpdatePlaylist(playlist);
      debugPrint('[YouTube] Created local playlist: $name (id: $newId)');
    } catch (e) {
      debugPrint('[YouTube] createPlaylist error: $e');
      rethrow;
    }
  }

  Future<void> updatePlaylist({
    required String playlistId,
    String? name,
    String? comment,
    List<String>? songIdsToAdd,
    List<int>? songIndexesToRemove,
  }) async {
    try {
      final existing = await _db.getPlaylist(playlistId);
      if (existing == null) {
        throw Exception('Playlist $playlistId not found in local library');
      }

      final currentSongs = List<Song>.from(existing.songs ?? []);

      // Remove songs by index if specified (descending order)
      if (songIndexesToRemove != null && songIndexesToRemove.isNotEmpty) {
        final sortedIndices = List<int>.from(songIndexesToRemove)..sort((a, b) => b.compareTo(a));
        for (final idx in sortedIndices) {
          if (idx >= 0 && idx < currentSongs.length) {
            currentSongs.removeAt(idx);
          }
        }
      }

      // Add songs if specified
      if (songIdsToAdd != null && songIdsToAdd.isNotEmpty) {
        for (final sid in songIdsToAdd) {
          final s = await _db.getSong(sid);
          if (s != null) {
            currentSongs.add(s);
          } else {
            // Fetch info online if not already in DB
            final info = await _ytdlp.getVideoInfo(sid);
            final newSong = info != null
                ? _mapDictToSong(info)
                : Song(id: sid, title: 'YouTube Track');
            await _db.insertOrUpdateSong(newSong);
            currentSongs.add(newSong);
          }
        }
      }

      final updated = existing.copyWith(
        name: name ?? existing.name,
        comment: comment ?? existing.comment,
        changed: DateTime.now(),
        songCount: currentSongs.length,
        coverArt: currentSongs.isNotEmpty ? currentSongs.first.coverArt : existing.coverArt,
        songs: currentSongs,
      );

      await _db.insertOrUpdatePlaylist(updated);
      debugPrint('[YouTube] Updated local playlist $playlistId (now ${currentSongs.length} songs)');
    } catch (e) {
      debugPrint('[YouTube] updatePlaylist error: $e');
      rethrow;
    }
  }

  Future<void> deletePlaylist(String id) async {
    try {
      await _db.deletePlaylist(id);
      debugPrint('[YouTube] Deleted local playlist: $id');
    } catch (e) {
      debugPrint('[YouTube] deletePlaylist error: $e');
      rethrow;
    }
  }

  // ── Search ────────────────────────────────────────────────────────────────

  Future<SearchResult> search(
    String query, {
    int artistCount = 20,
    int albumCount = 20,
    int songCount = 20,
  }) async {
    try {
      // 1. Query online tracks via yt-dlp dual search (YouTube Music + YouTube Video)
      final dualResults = await _ytdlp.searchDual(query, limit: songCount);
      final musicSongs = (dualResults['music'] ?? []).map(_mapDictToSong).toList();
      final youtubeVideos = (dualResults['youtube'] ?? []).map(_mapDictToSong).toList();

      // Cache songs in local SQLite database for future playlist & star operations
      for (final song in [...musicSongs, ...youtubeVideos]) {
        _db.insertOrUpdateSong(song).catchError((_) {});
      }

      // 2. Query local matching songs
      final localSongs = await _db.searchSongs(query, limit: songCount);

      // Merge online YouTube Music songs with local matches without duplicates
      final mergedMusic = <Song>[...musicSongs];
      final seenIds = musicSongs.map((s) => s.id).toSet();
      for (final ls in localSongs) {
        if (!seenIds.contains(ls.id)) {
          mergedMusic.add(ls);
          seenIds.add(ls.id);
        }
      }

      // Build artist & album suggestions from results
      final artists = <Artist>[];
      final albums = <Album>[];
      final seenArtists = <String>{};
      final seenAlbums = <String>{};

      for (final s in [...mergedMusic, ...youtubeVideos]) {
        if (s.artist != null && s.artist!.isNotEmpty && !seenArtists.contains(s.artist)) {
          seenArtists.add(s.artist!);
          artists.add(Artist(id: s.artistId ?? s.artist!, name: s.artist!, coverArt: s.coverArt));
        }
        if (s.album != null && s.album!.isNotEmpty && !seenAlbums.contains(s.album)) {
          seenAlbums.add(s.album!);
          albums.add(Album(id: s.albumId ?? s.album!, name: s.album!, artist: s.artist, coverArt: s.coverArt));
        }
      }

      return SearchResult(
        artists: artists.take(artistCount).toList(),
        albums: albums.take(albumCount).toList(),
        songs: mergedMusic.take(songCount).toList(),
        youtubeVideos: youtubeVideos.take(songCount).toList(),
      );
    } catch (e) {
      debugPrint('[YouTube] search error: $e');
      return SearchResult(artists: [], albums: [], songs: []);
    }
  }

  // ── Random / Trending songs ───────────────────────────────────────────────

  Future<List<Song>> getRandomSongs({int size = 20, String? genre}) async {
    try {
      final query = genre != null && genre.isNotEmpty
          ? '$genre music hits'
          : 'top music hits 2026';
      final rawResults = await _ytdlp.search(query, limit: size);
      final songs = rawResults.map(_mapDictToSong).toList();

      for (final song in songs) {
        _db.insertOrUpdateSong(song).catchError((_) {});
      }

      return songs;
    } catch (e) {
      debugPrint('[YouTube] getRandomSongs error: $e');
      return [];
    }
  }

  // ── Favorites (Saved in SQLite) ───────────────────────────────────────────

  Future<void> star({String? id, String? albumId, String? artistId}) async {
    try {
      if (id != null) {
        await _db.setSongStarred(id, true);
        final existing = await _db.getSong(id);
        if (existing == null) {
          final info = await _ytdlp.getVideoInfo(id);
          if (info != null) {
            await _db.insertOrUpdateSong(_mapDictToSong(info).copyWith(starred: true));
          }
        }
        debugPrint('[YouTube] Starred song $id locally');
      }
      if (albumId != null) {
        await _db.setAlbumStarred(albumId, true);
      }
    } catch (e) {
      debugPrint('[YouTube] star error: $e');
    }
  }

  Future<void> unstar({String? id, String? albumId, String? artistId}) async {
    try {
      if (id != null) {
        await _db.setSongStarred(id, false);
        debugPrint('[YouTube] Unstarred song $id locally');
      }
      if (albumId != null) {
        await _db.setAlbumStarred(albumId, false);
      }
    } catch (e) {
      debugPrint('[YouTube] unstar error: $e');
    }
  }

  Future<void> scrobble(String id, {bool submission = true}) async {
    // Record to local playback history
    debugPrint('[YouTube] Scrobble song $id (submission=$submission)');
  }

  Future<SearchResult> getStarred() async {
    try {
      final songs = await _db.getStarredSongs();
      final albums = await _db.getStarredAlbums();
      return SearchResult(artists: [], albums: albums, songs: songs);
    } catch (e) {
      debugPrint('[YouTube] getStarred error: $e');
      return SearchResult(artists: [], albums: [], songs: []);
    }
  }

  // ── Genres ────────────────────────────────────────────────────────────────

  Future<List<Genre>> getGenres() async {
    return [
      Genre(value: 'Pop', songCount: 50, albumCount: 10),
      Genre(value: 'Rock', songCount: 50, albumCount: 10),
      Genre(value: 'Hip-Hop / Rap', songCount: 50, albumCount: 10),
      Genre(value: 'R&B / Soul', songCount: 50, albumCount: 10),
      Genre(value: 'Electronic / Dance', songCount: 50, albumCount: 10),
      Genre(value: 'Indie / Alternative', songCount: 50, albumCount: 10),
      Genre(value: 'Classical', songCount: 50, albumCount: 10),
      Genre(value: 'Jazz', songCount: 50, albumCount: 10),
      Genre(value: 'Italian / Sanremo', songCount: 50, albumCount: 10),
      Genre(value: 'Acoustic / Lo-Fi', songCount: 50, albumCount: 10),
    ];
  }

  Future<List<Song>> getSongsByGenre(
    String genre, {
    int size = 50,
    int offset = 0,
  }) async {
    try {
      final rawResults = await _ytdlp.search('$genre music hits', limit: size + offset);
      final songs = rawResults.map(_mapDictToSong).toList();
      return songs.skip(offset).take(size).toList();
    } catch (e) {
      debugPrint('[YouTube] getSongsByGenre error: $e');
      return [];
    }
  }

  Future<List<Album>> getAlbumsByGenre(
    String genre, {
    int size = 50,
    int offset = 0,
  }) async =>
      [];

  // ── Related / Top songs ───────────────────────────────────────────────────

  Future<List<Song>> getSimilarSongs(String videoId, {int count = 50}) async {
    try {
      final radioRaw = await _ytdlp.getRadioTracks(videoId, limit: count);
      if (radioRaw.isNotEmpty) {
        final songs = radioRaw.map(_mapDictToSong).toList();
        for (final song in songs) {
          _db.insertOrUpdateSong(song).catchError((_) {});
        }
        return songs;
      }

      final info = await _ytdlp.getVideoInfo(videoId);
      final query = info != null
          ? '${info['artist'] ?? ''} ${info['title'] ?? ''} audio'
          : 'recommended music';
      final rawResults = await _ytdlp.search(query, limit: count);
      final songs = rawResults.map(_mapDictToSong).toList();
      for (final song in songs) {
        _db.insertOrUpdateSong(song).catchError((_) {});
      }
      return songs;
    } catch (e) {
      debugPrint('[YouTube] getSimilarSongs error: $e');
      return [];
    }
  }

  Future<List<Song>> getArtistTopSongs(
    String channelId, {
    int count = 50,
  }) async {
    try {
      final rawResults = await _ytdlp.search('$channelId top songs', limit: count);
      return rawResults.map(_mapDictToSong).toList();
    } catch (e) {
      debugPrint('[YouTube] getArtistTopSongs error: $e');
      return [];
    }
  }
}
