org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=256m -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError
kotlin.daemon.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m
org.gradle.vfs.watch=false
android.useAndroidX=true
android.newDsl=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
